name: getflutter
description: GetFlutter is open source libraries that come with pre-build 1000+ UI components. We build this library to make flutter development faster and more enjoyable. You can customize the component as you will build own app without UI knowledge.
version: 0.0.1-pre.3
#author: GetFlutter <info@getflutter.dev>
homepage: https://github.com/ionicfirebaseapp/getflutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
