name: getwidget
description: GetWidget is open source libraries that come with pre-build 1000+ UI components. It makes development faster & more enjoyable. You can customize the component as per your need.
version: 2.0.0-nullsafety
homepage: https://github.com/ionicfirebaseapp/getwidget

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  image_test_utils: ^1.0.0

flutter:
  uses-material-design: true
