name: getwidget
description: GetWidget is open source library that come with pre-build 1000+ UI components. It makes development faster & more enjoyable. You can customize the component as per your need.
version: 2.0.5
homepage: https://github.com/ionicfirebaseapp/getwidget

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - icons/assets/github.svg
    - icons/assets/logo.svg
    - icons/assets/playstore.svg
    - icons/whatsapp.png
    - icons/google.png
    - icons/facebook.png
    - icons/twitter.png
    - icons/dribble.png
    - icons/linkedin.png
    - icons/youtube.png
    - icons/slack.png
    - icons/pinterest.png
    - icons/wechat.png
    - icons/line.png
