name: gf_web
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  ui_kit:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo.png
    - lib/assets/icons/next.png
    - lib/assets/screen.png
